
# tap repositories and their packages

tap homebrew/core
brew act
brew aom
brew autoconf
brew autojump
brew bash
brew bash-completion
brew bat
brew boost
brew brotli
brew bzt
brew c-ares
brew ca-certificates
brew cairo
brew certifi
brew cffi
brew cheat
brew cmake
brew cocoapods
brew cython
brew deno
brew docker
brew docker-completion
brew docker-compose
brew double-conversion
brew edencommon
brew emscripten
brew eslint
brew exercism
brew fb303
brew fbthrift
brew fd
brew fish
brew fizz
brew fmt
brew folly
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew fzf
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gflags
brew gh
brew giflib
brew glib
brew glog
brew gmp
brew go
brew gobject-introspection
brew graphite2
brew graphviz
brew gts
brew harfbuzz
brew highway
brew icu4c
brew icu4c@75
brew imath
brew isl
brew jasper
brew jpeg-turbo
brew jpeg-xl
brew jq
brew keyring
brew krb5
brew libavif
brew libdeflate
brew libevent
brew libgit2
brew libgit2@1.7
brew libidn2
brew libmpc
brew libnghttp2
brew libpng
brew libpq
brew librsvg
brew libsodium
brew libspiro
brew libssh2
brew libtermkey
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libuv
brew libvmaf
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew llvm
brew lpeg
brew lua
brew luajit
brew luv
brew lz4
brew lzo
brew m4
brew mas
brew mpdecimal
brew mpfr
brew msgpack
brew mvfst
brew ncurses
brew neovide
brew neovim
brew netpbm
brew node
brew node-build
brew nodenv
brew numpy
brew oniguruma
brew openblas
brew openexr
brew openjdk
brew openssl@3
brew pango
brew pcre2
brew peco
brew pixman
brew pkg-config
brew poetry
brew postgresql@14
brew py3cairo
brew pycparser
brew pygobject3
brew python-build
brew python-packaging
brew python-setuptools
brew python@3.12
brew rbenv
brew readline
brew ripgrep
brew ruby
brew ruby-build
brew rust
brew rustup
brew six
brew snappy
brew sqlite
brew starship
brew tig
brew tree
brew tree-sitter
brew unibilium
brew virtualenv
brew wangle
brew watchman
brew webp
brew wget
brew woff2
brew xorgproto
brew xxhash
brew xz
brew yarn
brew yuicompressor
brew z
brew z3
brew zola
brew zoxide
brew zplug
brew zstd

tap homebrew/cask
cask aquaskk
cask chatgpt
cask discord
cask docker
cask font-plemol-jp
cask keycastr
cask lapce
cask neovide
cask notion
cask obsidian
cask qmk-toolbox
cask raycast
cask typora
cask visual-studio-code
cask vivaldi
cask warp
cask wezterm
cask zoom

tap homebrew/services

tap grishka/grishka
cask neardrop

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew openssl@3.0
brew python

# App Store applications
appstore 302584613 Amazon Kindle (7.21)
appstore 682658836 GarageBand (10.4.11)
appstore 408981434 iMovie (10.4.1)
appstore 409183694 Keynote (14.1)
appstore 539883307 LINE (9.3.0)
appstore 1219074514 Linearity Curve (5.13.0)
appstore 634148309 Logic Pro X (11.0.1)
appstore 1017470484 Next Meeting (2.7)
appstore 409203825 Numbers (14.1)
appstore 409201541 Pages (14.1)
appstore 1429033973 RunCat (11.4)
appstore 425955336 Skitch (2.9)
appstore 803453959 Slack (4.40.133)
appstore 497799835 Xcode (16.0)
