
# tap repositories and their packages

tap homebrew/core
brew act
brew aom
brew autoconf
brew autojump
brew bash
brew bash-completion
brew bat
brew boost
brew brew-pip
brew brotli
brew bzt
brew c-ares
brew ca-certificates
brew cairo
brew cffi
brew cheat
brew cmake
brew cocoapods
brew cython
brew deno
brew docker
brew docker-completion
brew docker-compose
brew double-conversion
brew edencommon
brew emscripten
brew eslint
brew exa
brew exercism
brew fb303
brew fbthrift
brew fd
brew fish
brew fizz
brew fmt
brew folly
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew fzf
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gflags
brew gh
brew giflib
brew glib
brew glog
brew gmp
brew gobject-introspection
brew graphite2
brew graphviz
brew gts
brew harfbuzz
brew highway
brew icu4c
brew imath
brew isl
brew jasper
brew jpeg-turbo
brew jpeg-xl
brew jq
brew keyring
brew krb5
brew libavif
brew libcython
brew libevent
brew libgit2
brew libidn2
brew libmpc
brew libnghttp2
brew libpng
brew libpq
brew librsvg
brew libsodium
brew libspiro
brew libssh2
brew libtermkey
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libuv
brew libvmaf
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lua
brew luajit
brew luv
brew lz4
brew lzo
brew m4
brew mpdecimal
brew mpfr
brew msgpack
brew ncurses
brew neovide
brew neovim
brew netpbm
brew node
brew node-build
brew nodenv
brew numpy
brew oniguruma
brew openblas
brew openexr
brew openjdk
brew openssl@1.1
brew openssl@3
brew pango
brew pcre2
brew peco
brew pixman
brew pkg-config
brew poetry
brew postgresql@14
brew py3cairo
brew pycparser
brew pygobject3
brew python-build
brew python-certifi
brew python-distlib
brew python-filelock
brew python-lxml
brew python-packaging
brew python-platformdirs
brew python-psutil
brew python-pyproject-hooks
brew python-pytz
brew python-setuptools
brew python@3.10
brew python@3.11
brew python@3.12
brew pyyaml
brew rbenv
brew readline
brew ripgrep
brew ruby
brew ruby-build
brew six
brew snappy
brew sqlite
brew tig
brew tree
brew tree-sitter
brew unibilium
brew virtualenv
brew wangle
brew watchman
brew webp
brew wget
brew woff2
brew xorgproto
brew xz
brew yarn
brew yuicompressor
brew z
brew zola
brew zstd

tap homebrew/cask
cask aquaskk
cask fig
cask keycastr
cask lapce
cask maccy
cask neovide
cask powershell
cask qmk-toolbox
cask visual-studio-code
cask wezterm

tap homebrew/cask-fonts
cask font-plemol-jp

tap homebrew/cask-versions

tap homebrew/services

tap grishka/grishka
cask neardrop

tap heroku/brew
brew heroku
brew heroku-node

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1219074514 Curve (5.3.0)
appstore 682658836 GarageBand (10.4.10)
appstore 408981434 iMovie (10.4)
appstore 409183694 Keynote (13.2)
appstore 539883307 LINE (8.5.3)
appstore 634148309 Logic Pro X (10.8.1)
appstore 1017470484 Next Meeting (2.7)
appstore 409203825 Numbers (13.2)
appstore 409201541 Pages (13.2)
appstore 1429033973 RunCat (10.3)
appstore 425955336 Skitch (2.9)
appstore 803453959 Slack (4.36.140)
appstore 497799835 Xcode (15.2)
